// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS9RHhkAjf1TE0X1Pq9eIKAZd3OYIfHBg',
    appId: '1:153878046588:web:5affcffbb1889095cee6f9',
    messagingSenderId: '153878046588',
    projectId: 'flutternode',
    authDomain: 'flutternode.firebaseapp.com',
    storageBucket: 'flutternode.appspot.com',
    measurementId: 'G-777HQTV2J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMi8vTroJ3yxz7QQzAIqGUwL_oj1tdO-o',
    appId: '1:153878046588:android:8a1982134d86df5bcee6f9',
    messagingSenderId: '153878046588',
    projectId: 'flutternode',
    storageBucket: 'flutternode.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5hfccaMMvDsiGhng6K_xoTCSV3QoTSUQ',
    appId: '1:153878046588:ios:060de26de8a02077cee6f9',
    messagingSenderId: '153878046588',
    projectId: 'flutternode',
    storageBucket: 'flutternode.appspot.com',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5hfccaMMvDsiGhng6K_xoTCSV3QoTSUQ',
    appId: '1:153878046588:ios:790548c0497f5b75cee6f9',
    messagingSenderId: '153878046588',
    projectId: 'flutternode',
    storageBucket: 'flutternode.appspot.com',
    iosBundleId: 'com.example.fnode',
  );
}
